spring.application.name=backend

# Server Port
server.port=8080


# Database Connection (Supabase IPv4 Session-Mode Pooler - Mumbai)
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.hjnxhlvsxnjhoqnurhzi
spring.datasource.password=Kavee#030513
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hikari Connection Pool Settings
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

